version: "3.5"
services:
 app-angular:
   container_name: app-angular-dev
   build: .
   volumes:
    - './src:/usr/app/src'
   ports:
    - '4201:4200'
   command: >
    bash -c "yarn install && yarn start"
